version: 2

jobs:
  deploy:
    docker:
      - image: circleci/python:3.8.1
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - restore_cache:
          keys:
            - poetry-{{ checksum "pyproject.toml" }}-{{ checksum "poetry.lock" }}
      - run:
          name: install
          command: |
            set -x

            poetry config virtualenvs.in-project true
            poetry install
      - save_cache:
          paths:
            - .venv
          key: poetry-{{ checksum "pyproject.toml" }}-{{ checksum "poetry.lock" }}
      - run:
          name: run
          command: |
            set -x
            poetry run ansible-playbook playbook.yml

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          context:
            - docker_config
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v([0-9]+\.){2}[0-9]+/